// <auto-generated />
using System;
using DeveloperGoals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveloperGoals.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105212403_ChangeUserIdToLong")]
    partial class ChangeUserIdToLong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeveloperGoals.Models.IgnoredTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiReasoning")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ContextTechnologyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IgnoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SystemDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Tag")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContextTechnologyId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name", "Category")
                        .IsUnique();

                    b.ToTable("IgnoredTechnologies");
                });

            modelBuilder.Entity("DeveloperGoals.Models.TechnologyDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SystemDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Tag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Prefix", "Tag")
                        .IsUnique();

                    b.ToTable("TechnologyDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Start",
                            Prefix = "System",
                            SystemDescription = "Węzeł startowy grafu technologii. Automatycznie tworzony dla każdego użytkownika.",
                            Tag = 1
                        });
                });

            modelBuilder.Entity("DeveloperGoals.Models.TechnologyDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FromTechnologyId")
                        .HasColumnType("integer");

                    b.Property<int>("ToTechnologyId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FromTechnologyId");

                    b.HasIndex("ToTechnologyId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "FromTechnologyId", "ToTechnologyId")
                        .IsUnique();

                    b.ToTable("TechnologyDependencies");
                });

            modelBuilder.Entity("DeveloperGoals.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DeveloperGoals.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DevelopmentArea")
                        .HasColumnType("integer");

                    b.Property<string>("MainTechnologies")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("DeveloperGoals.Models.UserTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiReasoning")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStart")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PrivateDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SystemDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Tag")
                        .HasColumnType("integer");

                    b.Property<int>("TechnologyDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyDefinitionId");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("UserTechnologies");
                });

            modelBuilder.Entity("DeveloperGoals.Models.IgnoredTechnology", b =>
                {
                    b.HasOne("DeveloperGoals.Models.UserTechnology", "ContextTechnology")
                        .WithMany()
                        .HasForeignKey("ContextTechnologyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DeveloperGoals.Models.User", "User")
                        .WithMany("IgnoredTechnologies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContextTechnology");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeveloperGoals.Models.TechnologyDependency", b =>
                {
                    b.HasOne("DeveloperGoals.Models.UserTechnology", "FromTechnology")
                        .WithMany()
                        .HasForeignKey("FromTechnologyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeveloperGoals.Models.UserTechnology", "ToTechnology")
                        .WithMany()
                        .HasForeignKey("ToTechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeveloperGoals.Models.User", "User")
                        .WithMany("TechnologyDependencies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromTechnology");

                    b.Navigation("ToTechnology");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeveloperGoals.Models.UserProfile", b =>
                {
                    b.HasOne("DeveloperGoals.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("DeveloperGoals.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeveloperGoals.Models.UserTechnology", b =>
                {
                    b.HasOne("DeveloperGoals.Models.TechnologyDefinition", "TechnologyDefinition")
                        .WithMany("UserTechnologies")
                        .HasForeignKey("TechnologyDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeveloperGoals.Models.User", "User")
                        .WithMany("Technologies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnologyDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeveloperGoals.Models.TechnologyDefinition", b =>
                {
                    b.Navigation("UserTechnologies");
                });

            modelBuilder.Entity("DeveloperGoals.Models.User", b =>
                {
                    b.Navigation("IgnoredTechnologies");

                    b.Navigation("Profile");

                    b.Navigation("Technologies");

                    b.Navigation("TechnologyDependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
